
Carbon:
  IncludeAssets:
    Packages:
      aa_Theme:
        Path:
          Inline:
            CSS: 'Public/Frontend/css'
            JS: 'Public/Frontend/lib'
          File:
            CSS: 'Public/Frontend/css'
            JS: 'Public/Frontend/lib'
        # Asset files who get's loaded in live and backend view
        General:
          Head:
            - main.css[inline]
            - aos.css[inline]
            - flickity.css[inline]
          Body:
            - main.js
            - shop.js
            - aos.js
            - flickity.js
            - lazysizes.min.js
